server:
  port: 9163
  
spring:
  application:
    name: longqin-zuul
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9160/eureka/  # 服务中心地址
      
zuul:
  host:
    connect-timeout-millis: 60000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时
    max-total-connections: 500
  routes:
    longqin-system:
      path: /**
      service-id: longqin-system
      sensitive-headers: "*"
    longqin-business:
      path: /bus/**
      service-id: longqin-business
      sensitive-headers: "*"

#熔断器的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 59000    #设置执行隔离时间为59秒
#hystrix.timeoutInMilliseconds   >=  ribbonTimeout = (ribbonReadTimeout + ribbonConnectTimeout) * (maxAutoRetries + 1) * (maxAutoRetriesNextServer + 1)
#ribbon超时设置
ribbon:
  ReadTimeout: 50000              #建立连接后从服务器读取到可用资源所用的时间
  SocketTimeout: 5000
  ConnectTimeout: 5000            #建立连接所用的时间,如果连接用时超过5秒就是抛出 java.net.SocketException: connetct time out 的异常
  MaxAutoRetries: 0               #对当前实例的重试次数(默认为0)
  MaxAutoRetriesNextServer: 0     #切换实例的重试次数(默认为0)
  OkToRetryOnAllOperations: true  #对所有操作请求都进行重试
    