server:
  port: 9161
  
spring:
  profiles:
    active: dev
  session:
    store-type: redis
    timeout: 10800
    redis:
      namespace: longqin
  application:
    name: longqin-system
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  resources:
    static-locations: classpath:static/,file:static/
  mail:
    host: smtp.qq.com
    username: 344589313@qq.com # 发件人邮箱
    nickname: 龙琴科技
    password: hmwcghzkhyijbjjf # 邮箱授权码
    default-encoding: UTF-8
    
mybatis:
  mapper-locations:
  - classpath:mapper/*Mapper.xml
  type-aliases-package: com.longqin.system.model
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9160/eureka/  # 服务中心地址
      
feign:
  httpclient:
    connection-timeout: 30000
  hystrix: 
    enabled: true
    
ribbon:
  ReadTimeout: 5000
  SocketTimeout: 5000
  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 12000